services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - "3030:27017"
        volumes:
            - ./mongodb_data:/data/db
        networks:
            - default
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
        depends_on:
            - mongo
        networks:
            - default
networks:
    default:
        name: mongodb_network
